// <auto-generated />
namespace Project.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CourseProfessorNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseProfessorNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201801172037540_CourseProfessorNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
